/**
 * Severn Edge AI - Trained Model Header
 * 
 * ============================================================================
 * THIS FILE IS AUTO-GENERATED BY THE WEB APPLICATION
 * ============================================================================
 * 
 * To update this model:
 * 1. Open the Severn Edge AI web application
 * 2. Connect to your Arduino and collect training data
 * 3. Train your model in the Train page
 * 4. Click "Export for Arduino" to download this file
 * 5. Replace this file with the downloaded model.h
 * 6. Rebuild and upload the firmware
 * 
 * Model Info (Placeholder):
 *   - Classes: 3 (Punch, Flex, Wave)
 *   - Input Shape: (100, 6) - 100 samples × 6 axes
 *   - Architecture: 1D CNN
 *   - Size: ~12KB
 */

#ifndef MODEL_H
#define MODEL_H

// ============================================================================
// PLACEHOLDER MODEL
// ============================================================================
// This is a minimal valid TFLite flatbuffer that will be replaced
// when you export a trained model from the web application.
// 
// The real model will be ~10-15KB and contain trained weights.

alignas(8) const unsigned char trained_model[] = {
    // TFLite Flatbuffer header (minimal placeholder)
    0x1c, 0x00, 0x00, 0x00, 0x54, 0x46, 0x4c, 0x33,  // TFL3 magic
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};

const unsigned int trained_model_len = sizeof(trained_model);

// Model metadata
#define MODEL_NUM_CLASSES 3
#define MODEL_WINDOW_SIZE 100
#define MODEL_NUM_AXES 6

// Class labels (customize these after training)
const char* const CLASS_LABELS[MODEL_NUM_CLASSES] = {
    "Punch",
    "Flex", 
    "Wave"
};

#endif // MODEL_H
